### ISSUE TITLE
Small code issue

### ISSUE THREAD

**Issue by Antek1234l** [schrodingerwastaken/cookieZ#1]
![image](https://user-images.githubusercontent.com/80584743/218875316-3aee8d82-6177-4db7-864a-eccbf18e1ffc.png)
It says "spotify", but it should be "pinterest"

**Comment by scchrodinger** [comment]
Thank you for your attention, sorry I didn't see your email.
Fixed :)

Antek1234l ***@***.***>, 15 Şub 2023 Çar, 01:15 tarihinde
şunu yazdı:
